"""System prompts for evaluation metrics."""

from .individual import (   # from .individual/all_prompts_v2
    OBSERVATION_ALIGNMENT_PROMPT,
    POLICY_ALIGNMENT_PROMPT,
    STATE_CONSISTENCY_PROMPT,
    TASK_COMPLETENESS_PROMPT,
    TOOL_PARAMETER_EXTRACTION_PROMPT,
    TOOL_SELECTION_PROMPT,
)

from .all_prompts_v2 import ( # from .mas/aall
    # MAS_COMPLEXITY_PROMPT_BASE_TEMPLATE,
    # MAS_PLANNING_PROMPT_BASE_TEMPLATE,
    # MAS_ROLES_DISTRIBUTION_PROMPT_BASE_TEMPLATE,
    # MAS_TASK_COMPLETION_PROMPT,
    # MAS_TASK_TRANSFER_PROMPT_BASE_TEMPLATE,
    TOOL_PERFORMANCE_PROMPT_BASE_TEMPLATE,
    PROMPT_QUALITY_PROMPT_BASE_TEMPLATE
)

from .mas import (
    MAS_COMPLEXITY_PROMPT_BASE_TEMPLATE,
    MAS_PLANNING_PROMPT_BASE_TEMPLATE,
    MAS_ROLES_DISTRIBUTION_PROMPT_BASE_TEMPLATE,
    MAS_TASK_COMPLETION_PROMPT,
    MAS_TASK_TRANSFER_PROMPT_BASE_TEMPLATE,
)

from .special import (
    MAS_SUMMARIZER_PROMPT_BASE_TEMPLATE,
    PLANNER_IDENTIFICATION_PROMPT_BASE_TEMPLATE,
    MAS_SUMMARIZER_PROMPT_BASE_TEMPLATE_BIN,
    MAS_SUMMARIZER_PROMPT_BASE_TEMPLATE_BIN_CONFIDENCE,
    MAS_UNIFIED_COMPREHENSIVE_EVALUATION_PROMPT
)


__all__ = [
    "OBSERVATION_ALIGNMENT_PROMPT",
    "POLICY_ALIGNMENT_PROMPT",
    "STATE_CONSISTENCY_PROMPT",
    "TASK_COMPLETENESS_PROMPT",
    "TOOL_PARAMETER_EXTRACTION_PROMPT",
    "TOOL_SELECTION_PROMPT",
    "MAS_COMPLEXITY_PROMPT_BASE_TEMPLATE",
    "MAS_PLANNING_PROMPT_BASE_TEMPLATE",
    "MAS_ROLES_DISTRIBUTION_PROMPT_BASE_TEMPLATE",
    "MAS_TASK_COMPLETION_PROMPT",
    "MAS_TASK_TRANSFER_PROMPT_BASE_TEMPLATE",
    "MAS_SUMMARIZER_PROMPT_BASE_TEMPLATE",
    "PLANNER_IDENTIFICATION_PROMPT_BASE_TEMPLATE",
    "MAS_SUMMARIZER_PROMPT_BASE_TEMPLATE_BIN",
    "MAS_SUMMARIZER_PROMPT_BASE_TEMPLATE_BIN_CONFIDENCE",
    "TOOL_PERFORMANCE_PROMPT_BASE_TEMPLATE",
    "PROMPT_QUALITY_PROMPT_BASE_TEMPLATE",
    "MAS_UNIFIED_COMPREHENSIVE_EVALUATION_PROMPT"
]
