"""Example trace parser for Langfuse format."""

from __future__ import annotations

import json
from datetime import datetime
from typing import Any

from maseval.models import (AgentResponse, AgentState, DialogueMessage,
                            EvaluationInput, MessageRole, StateType, ToolCall,
                            ToolDefinition)


def parse_langfuse_trace(trace_data: dict[str, Any]) -> EvaluationInput:
    """Parse a Langfuse trace into our EvaluationInput format.

    Args:
        trace_data: Raw trace data from Langfuse

    Returns:
        EvaluationInput: Parsed evaluation input
    """
    trace = trace_data["trace"]
    observations = trace_data["observations"]

    # Parse dialogue history from trace input/output
    dialogue_history = _parse_dialogue_from_trace(trace)

    # Parse agent responses and states from observations
    agent_responses, agent_states = _parse_observations(observations)

    # Extract available tools (if any)
    available_tools = _extract_tool_definitions(observations)

    return EvaluationInput(
        trace_id=trace["id"],
        session_id=trace.get("sessionId"),
        environment=trace.get("environment", "default"),
        dialogue_history=dialogue_history,
        agent_responses=agent_responses,
        agent_states=agent_states,
        available_tools=available_tools,
        metadata={
            "project_id": trace.get("projectId"),
            "latency": trace.get("latency"),
            "created_at": trace.get("createdAt"),
        },
    )


def _parse_dialogue_from_trace(trace: dict[str, Any]) -> list[DialogueMessage]:
    """Parse dialogue history from trace input/output."""
    dialogue = []

    # Parse input if it contains messages
    if "input" in trace:
        try:
            # Handle double-encoded JSON strings
            input_str = trace["input"]
            if (
                isinstance(input_str, str)
                and input_str.startswith('"')
                and input_str.endswith('"')
            ):
                # Remove outer quotes if present
                input_str = json.loads(input_str)

            input_data = json.loads(input_str)
            if "messages" in input_data:
                for msg in input_data["messages"]:
                    role = _map_role(msg.get("role", "user"))
                    content = msg.get("content", "")
                    dialogue.append(DialogueMessage(role=role, content=content))
        except (json.JSONDecodeError, KeyError, TypeError):
            # If parsing fails, treat as simple string input
            dialogue.append(
                DialogueMessage(role=MessageRole.USER, content=str(trace["input"]))
            )

    # Parse output if it contains messages
    if "output" in trace:
        try:
            # Handle double-encoded JSON strings
            output_str = trace["output"]
            if (
                isinstance(output_str, str)
                and output_str.startswith('"')
                and output_str.endswith('"')
            ):
                # Remove outer quotes if present
                output_str = json.loads(output_str)

            output_data = json.loads(output_str)
            if "messages" in output_data:
                for msg in output_data["messages"]:
                    role = _map_role(msg.get("type", "ai"))
                    content = msg.get("content", "")

                    # Skip tool messages for dialogue history (they'll be in states)
                    if role not in [MessageRole.TOOL]:
                        dialogue.append(
                            DialogueMessage(role=role, content=content, metadata=msg)
                        )
        except (json.JSONDecodeError, KeyError, TypeError):
            # If parsing fails, treat as simple string output
            dialogue.append(
                DialogueMessage(
                    role=MessageRole.ASSISTANT, content=str(trace["output"])
                )
            )

    return dialogue


def _parse_observations(
    observations: list[dict[str, Any]],
) -> tuple[list[AgentResponse], list[AgentState]]:
    """Parse agent responses and states from observations."""
    agent_responses = []
    agent_states = []

    for obs in observations:
        obs_type = obs.get("type", "").upper()
        obs_id = obs.get("id", "")
        obs_name = obs.get("name", "")

        if obs_type == "GENERATION":
            # This is typically an LLM generation - treat as agent response
            response = AgentResponse(
                response_id=obs_id,
                content=f"Generated by {obs_name}",
                timestamp=_parse_timestamp(obs.get("startTime")),
                metadata=obs,
            )
            agent_responses.append(response)

            # Also create a state for the generation
            state = AgentState(
                state_id=obs_id,
                type=StateType.THOUGHT,
                content=f"LLM generation using {obs.get('model', 'unknown model')}",
                timestamp=_parse_timestamp(obs.get("startTime")),
                metadata=obs,
            )
            agent_states.append(state)

        elif obs_type == "TOOL":
            # Tool usage
            tool_call = ToolCall(
                name=obs_name,
                parameters={},  # Tool parameters would need to be extracted from metadata
                result=None,  # Tool result would be in a separate observation
            )

            state = AgentState(
                state_id=obs_id,
                type=StateType.TOOL_CALL,
                content=f"Tool call: {obs_name}",
                tool_call=tool_call,
                timestamp=_parse_timestamp(obs.get("startTime")),
                metadata=obs,
            )
            agent_states.append(state)

        elif obs_type == "CHAIN":
            # Chain execution - treat as action state
            state = AgentState(
                state_id=obs_id,
                type=StateType.ACTION,
                content=f"Chain execution: {obs_name}",
                timestamp=_parse_timestamp(obs.get("startTime")),
                metadata=obs,
            )
            agent_states.append(state)

    return agent_responses, agent_states


def _extract_tool_definitions(
    observations: list[dict[str, Any]],
) -> list[ToolDefinition]:
    """Extract tool definitions from observations."""
    tools = []
    seen_tools = set()

    for obs in observations:
        if obs.get("type") == "TOOL":
            tool_name = obs.get("name", "")
            if tool_name and tool_name not in seen_tools:
                tools.append(
                    ToolDefinition(
                        name=tool_name,
                        description=f"Tool: {tool_name}",
                        parameters={},  # Would need to be extracted from metadata
                    )
                )
                seen_tools.add(tool_name)

    return tools


def _map_role(role_str: str) -> MessageRole:
    """Map various role strings to our MessageRole enum."""
    role_str = role_str.lower()

    role_mapping = {
        "user": MessageRole.USER,
        "human": MessageRole.USER,
        "assistant": MessageRole.ASSISTANT,
        "ai": MessageRole.ASSISTANT,
        "system": MessageRole.SYSTEM,
        "tool": MessageRole.TOOL,
    }

    return role_mapping.get(role_str, MessageRole.USER)


def _parse_timestamp(timestamp_str: str | None) -> datetime | None:
    """Parse timestamp string to datetime."""
    if not timestamp_str:
        return None

    try:
        # Handle ISO format with Z suffix
        if timestamp_str.endswith("Z"):
            timestamp_str = timestamp_str[:-1] + "+00:00"
        return datetime.fromisoformat(timestamp_str)
    except (ValueError, TypeError):
        return None


if __name__ == "__main__":
    # Example usage
    with open("../data/trace_example.json", "r") as f:
        trace_data = json.load(f)

    eval_input = parse_langfuse_trace(trace_data)
    print(f"Parsed trace with {len(eval_input.dialogue_history)} dialogue messages")
    print(f"Found {len(eval_input.agent_responses)} agent responses")
    print(f"Found {len(eval_input.agent_states)} agent states")
    print(f"Found {len(eval_input.available_tools)} tools")

    # Print some details
    for i, msg in enumerate(eval_input.dialogue_history):
        print(f"Message {i}: {msg.role} - {msg.content[:100]}...")
